version: '3.3'
services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - ${DB_PORT_DOCKER}:${DB_PORT}
    restart: unless-stopped

  backend:
    tty: true
    container_name: hubla-back-challenge
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src
    depends_on:
      - database

  frontend:
    container_name: hubla-front-challenge
    build:
      context: ./client
      dockerfile: Dockerfile
    image: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./client:/app
    depends_on:
      - backend
